"""create proposals table

Revision ID: 2dc936807817
Revises: 3ce7aece62b0
Create Date: 2026-03-31 01:16:10.913385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc936807817'
down_revision: Union[str, Sequence[str], None] = '3ce7aece62b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False, server_default='1'),
    sa.Column('proposal_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('problem_statement', sa.Text(), nullable=False),
    sa.Column('proposed_approach', sa.JSON(), nullable=False),
    sa.Column('timeline', sa.String(length=255), nullable=False),
    sa.Column('pricing_table', sa.JSON(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False, server_default='USD'),
    sa.Column('status', sa.String(length=50), nullable=False, server_default='Draft'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_lead_id'), 'proposals', ['lead_id'], unique=False)
    op.create_index(op.f('ix_proposals_user_id'), 'proposals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposals_user_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_lead_id'), table_name='proposals')
    op.drop_table('proposals')
    # ### end Alembic commands ###
