"""create outreach_messages table

Revision ID: 3ce7aece62b0
Revises: 1a95daf3d5f0
Create Date: 2026-03-31 00:59:23.510097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ce7aece62b0'
down_revision: Union[str, Sequence[str], None] = '1a95daf3d5f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outreach_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('subject_line', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_messages_lead_id'), 'outreach_messages', ['lead_id'], unique=False)
    op.create_index(op.f('ix_outreach_messages_user_id'), 'outreach_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outreach_messages_user_id'), table_name='outreach_messages')
    op.drop_index(op.f('ix_outreach_messages_lead_id'), table_name='outreach_messages')
    op.drop_table('outreach_messages')
    # ### end Alembic commands ###
